// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: pkg/grpc/fedi_instance.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFediInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFediInstanceRequest) Reset() {
	*x = GetFediInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fedi_instance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFediInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFediInstanceRequest) ProtoMessage() {}

func (x *GetFediInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fedi_instance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFediInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetFediInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fedi_instance_proto_rawDescGZIP(), []int{0}
}

func (x *GetFediInstanceRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFediInstanceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Domain         string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	ServerHostname string `protobuf:"bytes,3,opt,name=server_hostname,json=serverHostname,proto3" json:"server_hostname,omitempty"`
	Software       string `protobuf:"bytes,4,opt,name=software,proto3" json:"software,omitempty"`
}

func (x *GetFediInstanceReply) Reset() {
	*x = GetFediInstanceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fedi_instance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFediInstanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFediInstanceReply) ProtoMessage() {}

func (x *GetFediInstanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fedi_instance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFediInstanceReply.ProtoReflect.Descriptor instead.
func (*GetFediInstanceReply) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fedi_instance_proto_rawDescGZIP(), []int{1}
}

func (x *GetFediInstanceReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFediInstanceReply) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetFediInstanceReply) GetServerHostname() string {
	if x != nil {
		return x.ServerHostname
	}
	return ""
}

func (x *GetFediInstanceReply) GetSoftware() string {
	if x != nil {
		return x.Software
	}
	return ""
}

var File_pkg_grpc_fedi_instance_proto protoreflect.FileDescriptor

var file_pkg_grpc_fedi_instance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x65, 0x64, 0x69, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d,
	0x66, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e,
	0x66, 0x65, 0x64, 0x69, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x28, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x83, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46,
	0x65, 0x64, 0x69, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x32, 0x8f, 0x01,
	0x0a, 0x0c, 0x46, 0x65, 0x64, 0x69, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x7f,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x35, 0x2e, 0x66, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x2e, 0x66, 0x65, 0x64, 0x69, 0x5f, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x66, 0x65, 0x64, 0x69, 0x74,
	0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x66, 0x65, 0x64, 0x69, 0x5f,
	0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x65,
	0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_fedi_instance_proto_rawDescOnce sync.Once
	file_pkg_grpc_fedi_instance_proto_rawDescData = file_pkg_grpc_fedi_instance_proto_rawDesc
)

func file_pkg_grpc_fedi_instance_proto_rawDescGZIP() []byte {
	file_pkg_grpc_fedi_instance_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_fedi_instance_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_fedi_instance_proto_rawDescData)
	})
	return file_pkg_grpc_fedi_instance_proto_rawDescData
}

var file_pkg_grpc_fedi_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_fedi_instance_proto_goTypes = []interface{}{
	(*GetFediInstanceRequest)(nil), // 0: feditools.login.fedi_instance.GetFediInstanceRequest
	(*GetFediInstanceReply)(nil),   // 1: feditools.login.fedi_instance.GetFediInstanceReply
}
var file_pkg_grpc_fedi_instance_proto_depIdxs = []int32{
	0, // 0: feditools.login.fedi_instance.FediInstance.GetFediInstance:input_type -> feditools.login.fedi_instance.GetFediInstanceRequest
	1, // 1: feditools.login.fedi_instance.FediInstance.GetFediInstance:output_type -> feditools.login.fedi_instance.GetFediInstanceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_fedi_instance_proto_init() }
func file_pkg_grpc_fedi_instance_proto_init() {
	if File_pkg_grpc_fedi_instance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_fedi_instance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFediInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fedi_instance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFediInstanceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_fedi_instance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_fedi_instance_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_fedi_instance_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_fedi_instance_proto_msgTypes,
	}.Build()
	File_pkg_grpc_fedi_instance_proto = out.File
	file_pkg_grpc_fedi_instance_proto_rawDesc = nil
	file_pkg_grpc_fedi_instance_proto_goTypes = nil
	file_pkg_grpc_fedi_instance_proto_depIdxs = nil
}
