// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: pkg/grpc/fedi_account.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFediAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFediAccountRequest) Reset() {
	*x = GetFediAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fedi_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFediAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFediAccountRequest) ProtoMessage() {}

func (x *GetFediAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fedi_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFediAccountRequest.ProtoReflect.Descriptor instead.
func (*GetFediAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fedi_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetFediAccountRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFediAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username    string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	InstanceId  int64  `protobuf:"varint,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsAdmin     bool   `protobuf:"varint,5,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
}

func (x *GetFediAccountReply) Reset() {
	*x = GetFediAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_fedi_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFediAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFediAccountReply) ProtoMessage() {}

func (x *GetFediAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_fedi_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFediAccountReply.ProtoReflect.Descriptor instead.
func (*GetFediAccountReply) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_fedi_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetFediAccountReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetFediAccountReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetFediAccountReply) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *GetFediAccountReply) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetFediAccountReply) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_pkg_grpc_fedi_account_proto protoreflect.FileDescriptor

var file_pkg_grpc_fedi_account_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x65, 0x64, 0x69, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x66,
	0x65, 0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x66,
	0x65, 0x64, 0x69, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x64, 0x69, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x32, 0x89, 0x01, 0x0a, 0x0b, 0x46, 0x65, 0x64, 0x69,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x7a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x65,
	0x64, 0x69, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x33, 0x2e, 0x66, 0x65, 0x64, 0x69,
	0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x66, 0x65, 0x64, 0x69,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x69,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31,
	0x2e, 0x66, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x2e, 0x66, 0x65, 0x64, 0x69, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x46, 0x65, 0x64, 0x69, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x66, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_grpc_fedi_account_proto_rawDescOnce sync.Once
	file_pkg_grpc_fedi_account_proto_rawDescData = file_pkg_grpc_fedi_account_proto_rawDesc
)

func file_pkg_grpc_fedi_account_proto_rawDescGZIP() []byte {
	file_pkg_grpc_fedi_account_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_fedi_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_fedi_account_proto_rawDescData)
	})
	return file_pkg_grpc_fedi_account_proto_rawDescData
}

var file_pkg_grpc_fedi_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_fedi_account_proto_goTypes = []interface{}{
	(*GetFediAccountRequest)(nil), // 0: feditools.login.fedi_account.GetFediAccountRequest
	(*GetFediAccountReply)(nil),   // 1: feditools.login.fedi_account.GetFediAccountReply
}
var file_pkg_grpc_fedi_account_proto_depIdxs = []int32{
	0, // 0: feditools.login.fedi_account.FediAccount.GetFediAccount:input_type -> feditools.login.fedi_account.GetFediAccountRequest
	1, // 1: feditools.login.fedi_account.FediAccount.GetFediAccount:output_type -> feditools.login.fedi_account.GetFediAccountReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_fedi_account_proto_init() }
func file_pkg_grpc_fedi_account_proto_init() {
	if File_pkg_grpc_fedi_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_fedi_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFediAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_fedi_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFediAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_fedi_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_fedi_account_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_fedi_account_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_fedi_account_proto_msgTypes,
	}.Build()
	File_pkg_grpc_fedi_account_proto = out.File
	file_pkg_grpc_fedi_account_proto_rawDesc = nil
	file_pkg_grpc_fedi_account_proto_goTypes = nil
	file_pkg_grpc_fedi_account_proto_depIdxs = nil
}
