// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: login.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginClient interface {
	GetFediAccount(ctx context.Context, in *GetFediAccountRequest, opts ...grpc.CallOption) (*FediAccount, error)
	GetFediInstance(ctx context.Context, in *GetFediInstanceRequest, opts ...grpc.CallOption) (*FediInstance, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Pong, error)
}

type loginClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginClient(cc grpc.ClientConnInterface) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) GetFediAccount(ctx context.Context, in *GetFediAccountRequest, opts ...grpc.CallOption) (*FediAccount, error) {
	out := new(FediAccount)
	err := c.cc.Invoke(ctx, "/tools.fedi.login.Login/GetFediAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) GetFediInstance(ctx context.Context, in *GetFediInstanceRequest, opts ...grpc.CallOption) (*FediInstance, error) {
	out := new(FediInstance)
	err := c.cc.Invoke(ctx, "/tools.fedi.login.Login/GetFediInstance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := c.cc.Invoke(ctx, "/tools.fedi.login.Login/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
// All implementations must embed UnimplementedLoginServer
// for forward compatibility
type LoginServer interface {
	GetFediAccount(context.Context, *GetFediAccountRequest) (*FediAccount, error)
	GetFediInstance(context.Context, *GetFediInstanceRequest) (*FediInstance, error)
	Ping(context.Context, *PingRequest) (*Pong, error)
	mustEmbedUnimplementedLoginServer()
}

// UnimplementedLoginServer must be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (UnimplementedLoginServer) GetFediAccount(context.Context, *GetFediAccountRequest) (*FediAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFediAccount not implemented")
}
func (UnimplementedLoginServer) GetFediInstance(context.Context, *GetFediInstanceRequest) (*FediInstance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFediInstance not implemented")
}
func (UnimplementedLoginServer) Ping(context.Context, *PingRequest) (*Pong, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLoginServer) mustEmbedUnimplementedLoginServer() {}

// UnsafeLoginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginServer will
// result in compilation errors.
type UnsafeLoginServer interface {
	mustEmbedUnimplementedLoginServer()
}

func RegisterLoginServer(s grpc.ServiceRegistrar, srv LoginServer) {
	s.RegisterService(&Login_ServiceDesc, srv)
}

func _Login_GetFediAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFediAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).GetFediAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tools.fedi.login.Login/GetFediAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).GetFediAccount(ctx, req.(*GetFediAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_GetFediInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFediInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).GetFediInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tools.fedi.login.Login/GetFediInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).GetFediInstance(ctx, req.(*GetFediInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tools.fedi.login.Login/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Login_ServiceDesc is the grpc.ServiceDesc for Login service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Login_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tools.fedi.login.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFediAccount",
			Handler:    _Login_GetFediAccount_Handler,
		},
		{
			MethodName: "GetFediInstance",
			Handler:    _Login_GetFediInstance_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Login_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}
